## Installation

In [ ]:
# pip install nba_api
# pip install pandas
# pip install requests

## Custom Header

In [1]:
headers  = {
    'Connection': 'keep-alive',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-token': 'true',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}

## Create a dataframe with Common Player Info

In [2]:
# import our packages
import pandas as pd
import requests
from nba_api.stats.static import players
from nba_api.stats.endpoints import commonplayerinfo

In [4]:
# get a full list of players
nba_players = players.get_players()
df = pd.DataFrame(nba_players)
df.sample(5)

         id         full_name first_name last_name  is_active
3758   2745       Kirk Snyder       Kirk    Snyder      False
2569  77493      Tharon Mayes     Tharon     Mayes      False
3316  77927          Hub Reed        Hub      Reed      False
2647  77542  Forrest McKenzie    Forrest  McKenzie      False
2915  77701      Louie Nelson      Louie    Nelson      False

In [5]:
# get a full list of player_ids that are active
active_player_ids = df.loc[(df['is_active'] == True), 'id'].to_list()
active_player_ids

[203500,
 1628389,
 200746,
 1629734,
 1629638,
 1628960,
 1628386,
 1628443,
 202329,
 1626147,
 203937,
 201583,
 203507,
 1628961,
 203648,
 2546,
 1628384,
 1627853,
 2772,
 201571,
 1629028,
 1628407,
 1628963,
 1628366,
 1628964,
 200826,
 203084,
 1629628,
 203115,
 1628966,
 201587,
 203382,
 203145,
 1629647,
 203078,
 1627736,
 201158,
 1628395,
 1627761,
 1627733,
 202722,
 201976,
 203920,
 1629048,
 202687,
 202357,
 202339,
 203992,
 202711,
 1629626,
 1628413,
 1629648,
 1629067,
 1626164,
 1628449,
 1628968,
 1629065,
 202340,
 1628396,
 1629714,
 1629649,
 1628969,
 1628970,
 1629052,
 1629151,
 1627763,
 1628415,
 1628971,
 1627759,
 1629650,
 1628425,
 1629718,
 1628972,
 1628973,
 1628418,
 203493,
 203504,
 202692,
 1629126,
 202710,
 203998,
 1629719,
 203484,
 1628427,
 203991,
 201960,
 1628975,
 1713,
 1628976,
 203487,
 1627936,
 1626161,
 2199,
 201163,
 1629597,
 1629185,
 1627737,
 1629109,
 1629634,
 203903,
 1629651,
 1629598,
 1628499,
 1629599,
 1628381,
 1628380,
 201144,
 1626192,
 1626188,
 1629076,
 202326,
 203496,
 203459,
 1628470,
 203109,
 1629633,
 203552,
 201939,
 203584,
 203076,
 202334,
 1629056,
 201942,
 203473,
 203521,
 1628978,
 1627767,
 1628977,
 203476,
 203915,
 1629029,
 1629652,
 1628422,
 1629635,
 1628408,
 201609,
 203083,
 201162,
 1627739,
 201142,
 1629035,
 1627740,
 201961,
 203954,
 203516,
 1629234,
 1628980,
 203957,
 1629605,
 202324,
 1626245,
 1628390,
 1628981,
 1627812,
 1627827,
 1627854,
 203095,
 1628368,
 1626187,
 204025,
 1628982,
 1628365,
 1629117,
 1629655,
 201568,
 204038,
 1629636,
 201188,
 200752,
 202331,
 201959,
 1628385,
 1628983,
 203497,
 1629164,
 203932,
 201569,
 1628984,
 1626203,
 203924,
 1627982,
 201980,
 203110,
 101123,
 203210,
 1629750,
 201145,
 201933,
 1629741,
 1629657,
 1629060,
 1628985,
 203501,
 201935,
 203090,
 1629607,
 1626149,
 203914,
 203925,
 202699,
 1627885,
 1628404,
 1628392,
 2617,
 1629637,
 202330,
 203089,
 1629608,
 1627823,
 1626195,
 1629639,
 1628987,
 1626209,
 1627741,
 201588,
 203524,
 1629658,
 1628988,
 201950,
 203200,
 1626178,
 1626158,
 203918,
 201143,
 1629659,
 1627863,
 2730,
 1629739,
 1628989,
 1629631,
 1628990,
 201586,
 2738,
 101141,
 204060,
 1627742,
 202681,
 1628371,
 1628411,
 1628402,
 1628367,
 1628382,
 202704,
 1628991,
 1629713,
 2544,
 1628518,
 1629610,
 1629660,
 1628993,
 1629168,
 1629661,
 201949,
 1629640,
 1626169,
 204020,
 203999,
 1627745,
 1626145,
 1627884,
 201599,
 202709,
 1629662,
 1626163,
 202683,
 1628379,
 1629742,
 203077,
 1629663,
 1628467,
 202688,
 1628995,
 1629723,
 1627788,
 1628436,
 2594,
 1629066,
 1628398,
 203897,
 1627746,
 203087,
 1629641,
 1629724,
 1627774,
 1627747,
 1628388,
 1629665,
 201584,
 1627814,
 203458,
 202695,
 203086,
 203081,
 1629642,
 1626172,
 201572,
 201577,
 201567,
 200768,
 1627789,
 1626168,
 1629133,
 203705,
 101133,
 1627748,
 1629611,
 1626246,
 1628374,
 1628997,
 1628998,
 1629725,
 1629103,
 1628412,
 1629726,
 202083,
 1627775,
 203468,
 204456,
 1629667,
 203926,
 201580,
 203585,
 1628035,
 1629162,
 203463,
 203895,
 1629740,
 1629001,
 1629002,
 203114,
 101139,
 203121,
 1626259,
 201988,
 200794,
 1629003,
 1628378,
 1628513,
 1629690,
 1628370,
 1629760,
 202734,
 1629630,
 1629752,
 202693,
 1628420,
 202694,
 1628405,
 1626144,
 1627749,
 1627750,
 1629058,
 203488,
 1629004,
 1627846,
 1626204,
 203894,
 2403,
 203526,
 1627777,
 203457,
 1629668,
 1629669,
 1628373,
 1629134,
 203994,
 1628021,
 1626220,
 203124,
 1628400,
 1626143,
 1629059,
 1629006,
 1629644,
 203506,
 203482,
 1629671,
 1626224,
 1626162,
 1629745,
 203953,
 202718,
 1629672,
 1628394,
 202335,
 1628383,
 101108,
 203901,
 1627780,
 203658,
 1629033,
 203486,
 1627751,
 1629738,
 1629044,
 1629673,
 1629645,
 1629008,
 203490,
 1626171,
 204001,
 203939,
 1626181,
 1627752,
 203944,
 1629729,
 1629629,
 200755,
 1629675,
 1629244,
 1626196,
 203085,
 203460,
 1629130,
 1629010,
 1629620,
 1629011,
 203922,
 1629676,
 200765,
 201565,
 203082,
 1626179,
 201937,
 1626156,
 1627734,
 1629677,
 203960,
 203967,
 203107,
 1629678,
 203471,
 203118,
 200757,
 1629012,
 1629013,
 1629621,
 202697,
 1627783,
 1629735,
 1627732,
 1628424,
 1629014,
 1629346,
 203935,
 202397,
 1629015,
 1628372,
 203503,
 1629034,
 1629016,
 1629622,
 1628410,
 1628403,
 1628369,
 201952,
 202066,
 1628464,
 202738,
 1629017,
 1629744,
 202691,
 202684,
 1629680,
 201229,
 1626157,
 1629018,
 1629019,
 200782,
 1629730,
 202323,
 1626167,
 202685,
 1627756,
 1627832,
 1629020,
 1629216,
 203943,
 202696,
 1629731,
 1629021,
 203079,
 202689,
 1629022,
 202322,
 1627820,
 1628476,
 202954,
 203933,
 1629023,
 1629139,
 1629682,
 1628778,
 1629683,
 201566,
 1629632,
 1628401,
 202355,
 203952,
 1629684,
 1629140,
 1629026,
 101150,
 101107,
 1629057,
 1628430,
 1629627,
 1628391,
 1629685,
 1626159,
 1626174,
 1629624,
 1626153,
 1629625,
 201152,
 1629027,
 203469,
 1627790,
 1627826]

In [6]:
# alternate is to use the get active players function.
active_players = players.get_active_players()

In [7]:
for person in active_players:
    print(person)

{'id': 203500, 'full_name': 'Steven Adams', 'first_name': 'Steven', 'last_name': 'Adams', 'is_active': True}
{'id': 1628389, 'full_name': 'Bam Adebayo', 'first_name': 'Bam', 'last_name': 'Adebayo', 'is_active': True}
{'id': 200746, 'full_name': 'LaMarcus Aldridge', 'first_name': 'LaMarcus', 'last_name': 'Aldridge', 'is_active': True}
{'id': 1629734, 'full_name': 'Kyle Alexander', 'first_name': 'Kyle', 'last_name': 'Alexander', 'is_active': True}
{'id': 1629638, 'full_name': 'Nickeil Alexander-Walker', 'first_name': 'Nickeil', 'last_name': 'Alexander-Walker', 'is_active': True}
{'id': 1628960, 'full_name': 'Grayson Allen', 'first_name': 'Grayson', 'last_name': 'Allen', 'is_active': True}
{'id': 1628386, 'full_name': 'Jarrett Allen', 'first_name': 'Jarrett', 'last_name': 'Allen', 'is_active': True}
{'id': 1628443, 'full_name': 'Kadeem Allen', 'first_name': 'Kadeem', 'last_name': 'Allen', 'is_active': True}
{'id': 202329, 'full_name': 'Al-Farouq Aminu', 'first_name': 'Al-Farouq', 'last_name': 'Aminu', 'is_active': True}
{'id': 1626147, 'full_name': 'Justin Anderson', 'first_name': 'Justin', 'last_name': 'Anderson', 'is_active': True}
{'id': 203937, 'full_name': 'Kyle Anderson', 'first_name': 'Kyle', 'last_name': 'Anderson', 'is_active': True}
{'id': 201583, 'full_name': 'Ryan Anderson', 'first_name': 'Ryan', 'last_name': 'Anderson', 'is_active': True}
{'id': 203507, 'full_name': 'Giannis Antetokounmpo', 'first_name': 'Giannis', 'last_name': 'Antetokounmpo', 'is_active': True}
{'id': 1628961, 'full_name': 'Kostas Antetokounmpo', 'first_name': 'Kostas', 'last_name': 'Antetokounmpo', 'is_active': True}
{'id': 203648, 'full_name': 'Thanasis Antetokounmpo', 'first_name': 'Thanasis', 'last_name': 'Antetokounmpo', 'is_active': True}
{'id': 2546, 'full_name': 'Carmelo Anthony', 'first_name': 'Carmelo', 'last_name': 'Anthony', 'is_active': True}
{'id': 1628384, 'full_name': 'OG Anunoby', 'first_name': 'OG', 'last_name': 'Anunoby', 'is_active': True}
{'id': 1627853, 'full_name': 'Ryan Arcidiacono', 'first_name': 'Ryan', 'last_name': 'Arcidiacono', 'is_active': True}
{'id': 2772, 'full_name': 'Trevor Ariza', 'first_name': 'Trevor', 'last_name': 'Ariza', 'is_active': True}
{'id': 201571, 'full_name': 'D.J. Augustin', 'first_name': 'D.J.', 'last_name': 'Augustin', 'is_active': True}
{'id': 1629028, 'full_name': 'Deandre Ayton', 'first_name': 'Deandre', 'last_name': 'Ayton', 'is_active': True}
{'id': 1628407, 'full_name': 'Dwayne Bacon', 'first_name': 'Dwayne', 'last_name': 'Bacon', 'is_active': True}
{'id': 1628963, 'full_name': 'Marvin Bagley III', 'first_name': 'Marvin', 'last_name': 'Bagley III', 'is_active': True}
{'id': 1628366, 'full_name': 'Lonzo Ball', 'first_name': 'Lonzo', 'last_name': 'Ball', 'is_active': True}
{'id': 1628964, 'full_name': 'Mo Bamba', 'first_name': 'Mo', 'last_name': 'Bamba', 'is_active': True}
{'id': 200826, 'full_name': 'J.J. Barea', 'first_name': 'J.J.', 'last_name': 'Barea', 'is_active': True}
{'id': 203084, 'full_name': 'Harrison Barnes', 'first_name': 'Harrison', 'last_name': 'Barnes', 'is_active': True}
{'id': 1629628, 'full_name': 'RJ Barrett', 'first_name': 'RJ', 'last_name': 'Barrett', 'is_active': True}
{'id': 203115, 'full_name': 'Will Barton', 'first_name': 'Will', 'last_name': 'Barton', 'is_active': True}
{'id': 1628966, 'full_name': 'Keita Bates-Diop', 'first_name': 'Keita', 'last_name': 'Bates-Diop', 'is_active': True}
{'id': 201587, 'full_name': 'Nicolas Batum', 'first_name': 'Nicolas', 'last_name': 'Batum', 'is_active': True}
{'id': 203382, 'full_name': 'Aron Baynes', 'first_name': 'Aron', 'last_name': 'Baynes', 'is_active': True}
{'id': 203145, 'full_name': 'Kent Bazemore', 'first_name': 'Kent', 'last_name': 'Bazemore', 'is_active': True}
{'id': 1629647, 'full_name': 'Darius Bazley', 'first_name': 'Darius', 'last_name': 'Bazley', 'is_active': True}
{'id': 203078, 'full_name': 'Bradley Beal', 'first_name': 'Bradley', 'last_name': 'Beal', 'is_active': True}
{'id': 1627736, 'full_name': 'Malik Beasley', 'first_name': 'Malik', 'last_name': 'Beasley', 'is_active': True}
{'id': 201158, 'full_name': 'Marco Belinelli', 'first_name': 'Marco', 'last_name': 'Belinelli', 'is_active': True}
{'id': 1628395, 'full_name': 'Jordan Bell', 'first_name': 'Jordan', 'last_name': 'Bell', 'is_active': True}
{'id': 1627761, 'full_name': "DeAndre' Bembry", 'first_name': "DeAndre'", 'last_name': 'Bembry', 'is_active': True}
{'id': 1627733, 'full_name': 'Dragan Bender', 'first_name': 'Dragan', 'last_name': 'Bender', 'is_active': True}
{'id': 202722, 'full_name': 'Davis Bertans', 'first_name': 'Davis', 'last_name': 'Bertans', 'is_active': True}
{'id': 201976, 'full_name': 'Patrick Beverley', 'first_name': 'Patrick', 'last_name': 'Beverley', 'is_active': True}
{'id': 203920, 'full_name': 'Khem Birch', 'first_name': 'Khem', 'last_name': 'Birch', 'is_active': True}
{'id': 1629048, 'full_name': 'Goga Bitadze', 'first_name': 'Goga', 'last_name': 'Bitadze', 'is_active': True}
{'id': 202687, 'full_name': 'Bismack Biyombo', 'first_name': 'Bismack', 'last_name': 'Biyombo', 'is_active': True}
{'id': 202357, 'full_name': 'Nemanja Bjelica', 'first_name': 'Nemanja', 'last_name': 'Bjelica', 'is_active': True}
{'id': 202339, 'full_name': 'Eric Bledsoe', 'first_name': 'Eric', 'last_name': 'Bledsoe', 'is_active': True}
{'id': 203992, 'full_name': 'Bogdan Bogdanovic', 'first_name': 'Bogdan', 'last_name': 'Bogdanovic', 'is_active': True}
{'id': 202711, 'full_name': 'Bojan Bogdanovic', 'first_name': 'Bojan', 'last_name': 'Bogdanovic', 'is_active': True}
{'id': 1629626, 'full_name': 'Bol Bol', 'first_name': 'Bol', 'last_name': 'Bol', 'is_active': True}
{'id': 1628413, 'full_name': 'Jonah Bolden', 'first_name': 'Jonah', 'last_name': 'Bolden', 'is_active': True}
{'id': 1629648, 'full_name': 'Jordan Bone', 'first_name': 'Jordan', 'last_name': 'Bone', 'is_active': True}
{'id': 1629067, 'full_name': 'Isaac Bonga', 'first_name': 'Isaac', 'last_name': 'Bonga', 'is_active': True}
{'id': 1626164, 'full_name': 'Devin Booker', 'first_name': 'Devin', 'last_name': 'Booker', 'is_active': True}
{'id': 1628449, 'full_name': 'Chris Boucher', 'first_name': 'Chris', 'last_name': 'Boucher', 'is_active': True}
{'id': 1628968, 'full_name': 'Brian Bowen II', 'first_name': 'Brian', 'last_name': 'Bowen II', 'is_active': True}
{'id': 1629065, 'full_name': 'Ky Bowman', 'first_name': 'Ky', 'last_name': 'Bowman', 'is_active': True}
{'id': 202340, 'full_name': 'Avery Bradley', 'first_name': 'Avery', 'last_name': 'Bradley', 'is_active': True}
{'id': 1628396, 'full_name': 'Tony Bradley', 'first_name': 'Tony', 'last_name': 'Bradley', 'is_active': True}
{'id': 1629714, 'full_name': 'Jarrell Brantley', 'first_name': 'Jarrell', 'last_name': 'Brantley', 'is_active': True}
{'id': 1629649, 'full_name': 'Ignas Brazdeikis', 'first_name': 'Ignas', 'last_name': 'Brazdeikis', 'is_active': True}
{'id': 1628969, 'full_name': 'Mikal Bridges', 'first_name': 'Mikal', 'last_name': 'Bridges', 'is_active': True}
{'id': 1628970, 'full_name': 'Miles Bridges', 'first_name': 'Miles', 'last_name': 'Bridges', 'is_active': True}
{'id': 1629052, 'full_name': 'Oshae Brissett', 'first_name': 'Oshae', 'last_name': 'Brissett', 'is_active': True}
{'id': 1629151, 'full_name': 'Ryan Broekhoff', 'first_name': 'Ryan', 'last_name': 'Broekhoff', 'is_active': True}
{'id': 1627763, 'full_name': 'Malcolm Brogdon', 'first_name': 'Malcolm', 'last_name': 'Brogdon', 'is_active': True}
{'id': 1628415, 'full_name': 'Dillon Brooks', 'first_name': 'Dillon', 'last_name': 'Brooks', 'is_active': True}
{'id': 1628971, 'full_name': 'Bruce Brown', 'first_name': 'Bruce', 'last_name': 'Brown', 'is_active': True}
{'id': 1627759, 'full_name': 'Jaylen Brown', 'first_name': 'Jaylen', 'last_name': 'Brown', 'is_active': True}
{'id': 1629650, 'full_name': 'Moses Brown', 'first_name': 'Moses', 'last_name': 'Brown', 'is_active': True}
{'id': 1628425, 'full_name': 'Sterling Brown', 'first_name': 'Sterling', 'last_name': 'Brown', 'is_active': True}
{'id': 1629718, 'full_name': 'Charles Brown Jr.', 'first_name': 'Charles', 'last_name': 'Brown Jr.', 'is_active': True}
{'id': 1628972, 'full_name': 'Troy Brown Jr.', 'first_name': 'Troy', 'last_name': 'Brown Jr.', 'is_active': True}
{'id': 1628973, 'full_name': 'Jalen Brunson', 'first_name': 'Jalen', 'last_name': 'Brunson', 'is_active': True}
{'id': 1628418, 'full_name': 'Thomas Bryant', 'first_name': 'Thomas', 'last_name': 'Bryant', 'is_active': True}
{'id': 203493, 'full_name': 'Reggie Bullock', 'first_name': 'Reggie', 'last_name': 'Bullock', 'is_active': True}
{'id': 203504, 'full_name': 'Trey Burke', 'first_name': 'Trey', 'last_name': 'Burke', 'is_active': True}
{'id': 202692, 'full_name': 'Alec Burks', 'first_name': 'Alec', 'last_name': 'Burks', 'is_active': True}
{'id': 1629126, 'full_name': 'Deonte Burton', 'first_name': 'Deonte', 'last_name': 'Burton', 'is_active': True}
{'id': 202710, 'full_name': 'Jimmy Butler', 'first_name': 'Jimmy', 'last_name': 'Butler', 'is_active': True}
{'id': 203998, 'full_name': 'Bruno Caboclo', 'first_name': 'Bruno', 'last_name': 'Caboclo', 'is_active': True}
{'id': 1629719, 'full_name': 'Devontae Cacok', 'first_name': 'Devontae', 'last_name': 'Cacok', 'is_active': True}
{'id': 203484, 'full_name': 'Kentavious Caldwell-Pope', 'first_name': 'Kentavious', 'last_name': 'Caldwell-Pope', 'is_active': True}
{'id': 1628427, 'full_name': 'Vlatko Cancar', 'first_name': 'Vlatko', 'last_name': 'Cancar', 'is_active': True}
{'id': 203991, 'full_name': 'Clint Capela', 'first_name': 'Clint', 'last_name': 'Capela', 'is_active': True}
{'id': 201960, 'full_name': 'DeMarre Carroll', 'first_name': 'DeMarre', 'last_name': 'Carroll', 'is_active': True}
{'id': 1628975, 'full_name': 'Jevon Carter', 'first_name': 'Jevon', 'last_name': 'Carter', 'is_active': True}
{'id': 1713, 'full_name': 'Vince Carter', 'first_name': 'Vince', 'last_name': 'Carter', 'is_active': True}
{'id': 1628976, 'full_name': 'Wendell Carter Jr.', 'first_name': 'Wendell', 'last_name': 'Carter Jr.', 'is_active': True}
{'id': 203487, 'full_name': 'Michael Carter-Williams', 'first_name': 'Michael', 'last_name': 'Carter-Williams', 'is_active': True}
{'id': 1627936, 'full_name': 'Alex Caruso', 'first_name': 'Alex', 'last_name': 'Caruso', 'is_active': True}
{'id': 1626161, 'full_name': 'Willie Cauley-Stein', 'first_name': 'Willie', 'last_name': 'Cauley-Stein', 'is_active': True}
{'id': 2199, 'full_name': 'Tyson Chandler', 'first_name': 'Tyson', 'last_name': 'Chandler', 'is_active': True}
{'id': 201163, 'full_name': 'Wilson Chandler', 'first_name': 'Wilson', 'last_name': 'Chandler', 'is_active': True}
{'id': 1629597, 'full_name': 'Zylan Cheatham', 'first_name': 'Zylan', 'last_name': 'Cheatham', 'is_active': True}
{'id': 1629185, 'full_name': 'Chris Chiozza', 'first_name': 'Chris', 'last_name': 'Chiozza', 'is_active': True}
{'id': 1627737, 'full_name': 'Marquese Chriss', 'first_name': 'Marquese', 'last_name': 'Chriss', 'is_active': True}
{'id': 1629109, 'full_name': 'Gary Clark', 'first_name': 'Gary', 'last_name': 'Clark', 'is_active': True}
{'id': 1629634, 'full_name': 'Brandon Clarke', 'first_name': 'Brandon', 'last_name': 'Clarke', 'is_active': True}
{'id': 203903, 'full_name': 'Jordan Clarkson', 'first_name': 'Jordan', 'last_name': 'Clarkson', 'is_active': True}
{'id': 1629651, 'full_name': 'Nicolas Claxton', 'first_name': 'Nicolas', 'last_name': 'Claxton', 'is_active': True}
{'id': 1629598, 'full_name': 'Chris Clemons', 'first_name': 'Chris', 'last_name': 'Clemons', 'is_active': True}
{'id': 1628499, 'full_name': 'Antonius Cleveland', 'first_name': 'Antonius', 'last_name': 'Cleveland', 'is_active': True}
{'id': 1629599, 'full_name': 'Amir Coffey', 'first_name': 'Amir', 'last_name': 'Coffey', 'is_active': True}
{'id': 1628381, 'full_name': 'John Collins', 'first_name': 'John', 'last_name': 'Collins', 'is_active': True}
{'id': 1628380, 'full_name': 'Zach Collins', 'first_name': 'Zach', 'last_name': 'Collins', 'is_active': True}
{'id': 201144, 'full_name': 'Mike Conley', 'first_name': 'Mike', 'last_name': 'Conley', 'is_active': True}
{'id': 1626192, 'full_name': 'Pat Connaughton', 'first_name': 'Pat', 'last_name': 'Connaughton', 'is_active': True}
{'id': 1626188, 'full_name': 'Quinn Cook', 'first_name': 'Quinn', 'last_name': 'Cook', 'is_active': True}
{'id': 1629076, 'full_name': 'Tyler Cook', 'first_name': 'Tyler', 'last_name': 'Cook', 'is_active': True}
{'id': 202326, 'full_name': 'DeMarcus Cousins', 'first_name': 'DeMarcus', 'last_name': 'Cousins', 'is_active': True}
{'id': 203496, 'full_name': 'Robert Covington', 'first_name': 'Robert', 'last_name': 'Covington', 'is_active': True}
{'id': 203459, 'full_name': 'Allen Crabbe', 'first_name': 'Allen', 'last_name': 'Crabbe', 'is_active': True}
{'id': 1628470, 'full_name': 'Torrey Craig', 'first_name': 'Torrey', 'last_name': 'Craig', 'is_active': True}
{'id': 203109, 'full_name': 'Jae Crowder', 'first_name': 'Jae', 'last_name': 'Crowder', 'is_active': True}
{'id': 1629633, 'full_name': 'Jarrett Culver', 'first_name': 'Jarrett', 'last_name': 'Culver', 'is_active': True}
{'id': 203552, 'full_name': 'Seth Curry', 'first_name': 'Seth', 'last_name': 'Curry', 'is_active': True}
{'id': 201939, 'full_name': 'Stephen Curry', 'first_name': 'Stephen', 'last_name': 'Curry', 'is_active': True}
{'id': 203584, 'full_name': 'Troy Daniels', 'first_name': 'Troy', 'last_name': 'Daniels', 'is_active': True}
{'id': 203076, 'full_name': 'Anthony Davis', 'first_name': 'Anthony', 'last_name': 'Davis', 'is_active': True}
{'id': 202334, 'full_name': 'Ed Davis', 'first_name': 'Ed', 'last_name': 'Davis', 'is_active': True}
{'id': 1629056, 'full_name': 'Terence Davis', 'first_name': 'Terence', 'last_name': 'Davis', 'is_active': True}
{'id': 201942, 'full_name': 'DeMar DeRozan', 'first_name': 'DeMar', 'last_name': 'DeRozan', 'is_active': True}
{'id': 203473, 'full_name': 'Dewayne Dedmon', 'first_name': 'Dewayne', 'last_name': 'Dedmon', 'is_active': True}
{'id': 203521, 'full_name': 'Matthew Dellavedova', 'first_name': 'Matthew', 'last_name': 'Dellavedova', 'is_active': True}
{'id': 1628978, 'full_name': 'Donte DiVincenzo', 'first_name': 'Donte', 'last_name': 'DiVincenzo', 'is_active': True}
{'id': 1627767, 'full_name': 'Cheick Diallo', 'first_name': 'Cheick', 'last_name': 'Diallo', 'is_active': True}
{'id': 1628977, 'full_name': 'Hamidou Diallo', 'first_name': 'Hamidou', 'last_name': 'Diallo', 'is_active': True}
{'id': 203476, 'full_name': 'Gorgui Dieng', 'first_name': 'Gorgui', 'last_name': 'Dieng', 'is_active': True}
{'id': 203915, 'full_name': 'Spencer Dinwiddie', 'first_name': 'Spencer', 'last_name': 'Dinwiddie', 'is_active': True}
{'id': 1629029, 'full_name': 'Luka Doncic', 'first_name': 'Luka', 'last_name': 'Doncic', 'is_active': True}
{'id': 1629652, 'full_name': 'Luguentz Dort', 'first_name': 'Luguentz', 'last_name': 'Dort', 'is_active': True}
{'id': 1628422, 'full_name': 'Damyean Dotson', 'first_name': 'Damyean', 'last_name': 'Dotson', 'is_active': True}
{'id': 1629635, 'full_name': 'Sekou Doumbouya', 'first_name': 'Sekou', 'last_name': 'Doumbouya', 'is_active': True}
{'id': 1628408, 'full_name': 'PJ Dozier', 'first_name': 'PJ', 'last_name': 'Dozier', 'is_active': True}
{'id': 201609, 'full_name': 'Goran Dragic', 'first_name': 'Goran', 'last_name': 'Dragic', 'is_active': True}
{'id': 203083, 'full_name': 'Andre Drummond', 'first_name': 'Andre', 'last_name': 'Drummond', 'is_active': True}
{'id': 201162, 'full_name': 'Jared Dudley', 'first_name': 'Jared', 'last_name': 'Dudley', 'is_active': True}
{'id': 1627739, 'full_name': 'Kris Dunn', 'first_name': 'Kris', 'last_name': 'Dunn', 'is_active': True}
{'id': 201142, 'full_name': 'Kevin Durant', 'first_name': 'Kevin', 'last_name': 'Durant', 'is_active': True}
{'id': 1629035, 'full_name': 'Carsen Edwards', 'first_name': 'Carsen', 'last_name': 'Edwards', 'is_active': True}
{'id': 1627740, 'full_name': 'Henry Ellenson', 'first_name': 'Henry', 'last_name': 'Ellenson', 'is_active': True}
{'id': 201961, 'full_name': 'Wayne Ellington', 'first_name': 'Wayne', 'last_name': 'Ellington', 'is_active': True}
{'id': 203954, 'full_name': 'Joel Embiid', 'first_name': 'Joel', 'last_name': 'Embiid', 'is_active': True}
{'id': 203516, 'full_name': 'James Ennis III', 'first_name': 'James', 'last_name': 'Ennis III', 'is_active': True}
{'id': 1629234, 'full_name': 'Drew Eubanks', 'first_name': 'Drew', 'last_name': 'Eubanks', 'is_active': True}
{'id': 1628980, 'full_name': 'Jacob Evans', 'first_name': 'Jacob', 'last_name': 'Evans', 'is_active': True}
{'id': 203957, 'full_name': 'Dante Exum', 'first_name': 'Dante', 'last_name': 'Exum', 'is_active': True}
{'id': 1629605, 'full_name': 'Tacko Fall', 'first_name': 'Tacko', 'last_name': 'Fall', 'is_active': True}
{'id': 202324, 'full_name': 'Derrick Favors', 'first_name': 'Derrick', 'last_name': 'Favors', 'is_active': True}
{'id': 1626245, 'full_name': 'Cristiano Felicio', 'first_name': 'Cristiano', 'last_name': 'Felicio', 'is_active': True}
{'id': 1628390, 'full_name': 'Terrance Ferguson', 'first_name': 'Terrance', 'last_name': 'Ferguson', 'is_active': True}
{'id': 1628981, 'full_name': 'Bruno Fernando', 'first_name': 'Bruno', 'last_name': 'Fernando', 'is_active': True}
{'id': 1627812, 'full_name': 'Yogi Ferrell', 'first_name': 'Yogi', 'last_name': 'Ferrell', 'is_active': True}
{'id': 1627827, 'full_name': 'Dorian Finney-Smith', 'first_name': 'Dorian', 'last_name': 'Finney-Smith', 'is_active': True}
{'id': 1627854, 'full_name': 'Bryn Forbes', 'first_name': 'Bryn', 'last_name': 'Forbes', 'is_active': True}
{'id': 203095, 'full_name': 'Evan Fournier', 'first_name': 'Evan', 'last_name': 'Fournier', 'is_active': True}
{'id': 1628368, 'full_name': "De'Aaron Fox", 'first_name': "De'Aaron", 'last_name': 'Fox', 'is_active': True}
{'id': 1626187, 'full_name': 'Michael Frazier', 'first_name': 'Michael', 'last_name': 'Frazier', 'is_active': True}
{'id': 204025, 'full_name': 'Tim Frazier', 'first_name': 'Tim', 'last_name': 'Frazier', 'is_active': True}
{'id': 1628982, 'full_name': 'Melvin Frazier Jr.', 'first_name': 'Melvin', 'last_name': 'Frazier Jr.', 'is_active': True}
{'id': 1628365, 'full_name': 'Markelle Fultz', 'first_name': 'Markelle', 'last_name': 'Fultz', 'is_active': True}
{'id': 1629117, 'full_name': 'Wenyen Gabriel', 'first_name': 'Wenyen', 'last_name': 'Gabriel', 'is_active': True}
{'id': 1629655, 'full_name': 'Daniel Gafford', 'first_name': 'Daniel', 'last_name': 'Gafford', 'is_active': True}
{'id': 201568, 'full_name': 'Danilo Gallinari', 'first_name': 'Danilo', 'last_name': 'Gallinari', 'is_active': True}
{'id': 204038, 'full_name': 'Langston Galloway', 'first_name': 'Langston', 'last_name': 'Galloway', 'is_active': True}
{'id': 1629636, 'full_name': 'Darius Garland', 'first_name': 'Darius', 'last_name': 'Garland', 'is_active': True}
{'id': 201188, 'full_name': 'Marc Gasol', 'first_name': 'Marc', 'last_name': 'Gasol', 'is_active': True}
{'id': 200752, 'full_name': 'Rudy Gay', 'first_name': 'Rudy', 'last_name': 'Gay', 'is_active': True}
{'id': 202331, 'full_name': 'Paul George', 'first_name': 'Paul', 'last_name': 'George', 'is_active': True}
{'id': 201959, 'full_name': 'Taj Gibson', 'first_name': 'Taj', 'last_name': 'Gibson', 'is_active': True}
{'id': 1628385, 'full_name': 'Harry Giles III', 'first_name': 'Harry', 'last_name': 'Giles III', 'is_active': True}
{'id': 1628983, 'full_name': 'Shai Gilgeous-Alexander', 'first_name': 'Shai', 'last_name': 'Gilgeous-Alexander', 'is_active': True}
{'id': 203497, 'full_name': 'Rudy Gobert', 'first_name': 'Rudy', 'last_name': 'Gobert', 'is_active': True}
{'id': 1629164, 'full_name': 'Brandon Goodwin', 'first_name': 'Brandon', 'last_name': 'Goodwin', 'is_active': True}
{'id': 203932, 'full_name': 'Aaron Gordon', 'first_name': 'Aaron', 'last_name': 'Gordon', 'is_active': True}
{'id': 201569, 'full_name': 'Eric Gordon', 'first_name': 'Eric', 'last_name': 'Gordon', 'is_active': True}

In [8]:
nba_player_id = '1628389'

In [9]:
player_info = commonplayerinfo.CommonPlayerInfo(player_id=nba_player_id, headers=headers, timeout=100)
df = player_info.common_player_info.get_data_frame()
df

,PERSON_ID,FIRST_NAME,LAST_NAME,DISPLAY_FIRST_LAST,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FI_LAST,PLAYER_SLUG,BIRTHDATE,SCHOOL,COUNTRY,...,TEAM_CITY,PLAYERCODE,FROM_YEAR,TO_YEAR,DLEAGUE_FLAG,NBA_FLAG,GAMES_PLAYED_FLAG,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER
0,1628389,Bam,Adebayo,Bam Adebayo,"Adebayo, Bam",B. Adebayo,bam-adebayo,1997-07-18T00:00:00,Kentucky,USA,...,Miami,bam_adebayo,2017,2021,N,Y,Y,2017,1,14

In [10]:
# create function that gets player info data
def get_player_data(nba_player_id):
    player_info = commonplayerinfo.CommonPlayerInfo(player_id=nba_player_id, headers=headers,timeout=100)
    df = player_info.common_player_info.get_data_frame()
    return df

In [11]:
sample_player_ids = [
    '203500',
    '1628389',
    '200746',
    '1629734',
    '1629638',
    '1628960',
    '1628386',
    '1628443',
    '202329',
    '1626147',
    '203937',
    '201583',
    '203507',
    '1628961',
    '203648',
    '2546',
    '1628384',
    '1627853',
    '2772',
    '201571',
]

In [12]:
player_data = []
for nba_player_id in sample_player_ids: 
# for nba_player_id in active_player_ids: # remove this when ready to run for full season
    print(nba_player_id)
    player_info = get_player_data(nba_player_id)
    player_data.append(player_info)
    #time.sleep(3)

final_df = pd.concat(player_data, ignore_index=True)

203500
1628389
200746
1629734
1629638
1628960
1628386
1628443
202329
1626147
203937
201583
203507
1628961
203648
2546
1628384
1627853
2772
201571

In [13]:
final_df.sample(20)

,PERSON_ID,FIRST_NAME,LAST_NAME,DISPLAY_FIRST_LAST,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FI_LAST,PLAYER_SLUG,BIRTHDATE,SCHOOL,COUNTRY,...,TEAM_CITY,PLAYERCODE,FROM_YEAR,TO_YEAR,DLEAGUE_FLAG,NBA_FLAG,GAMES_PLAYED_FLAG,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER
15,2546,Carmelo,Anthony,Carmelo Anthony,"Anthony, Carmelo",C. Anthony,carmelo-anthony,1984-05-29T00:00:00,Syracuse,USA,...,Los Angeles,carmelo_anthony,2003,2021,N,Y,Y,2003,1,3
10,203937,Kyle,Anderson,Kyle Anderson,"Anderson, Kyle",K. Anderson,kyle-anderson,1993-09-20T00:00:00,UCLA,USA,...,Memphis,kyle_anderson,2014,2021,Y,Y,Y,2014,1,30
2,200746,LaMarcus,Aldridge,LaMarcus Aldridge,"Aldridge, LaMarcus",L. Aldridge,lamarcus-aldridge,1985-07-19T00:00:00,University of Texas at Austin,USA,...,,lamarcus_aldridge,2006,2020,N,Y,Y,2006,1,2
4,1629638,Nickeil,Alexander-Walker,Nickeil Alexander-Walker,"Alexander-Walker, Nickeil",N. Alexander-Walker,nickeil-alexander-walker,1998-09-02T00:00:00,Virginia Tech,Canada,...,New Orleans,nickeil_alexander-walker,2019,2021,Y,Y,Y,2019,1,17
3,1629734,Kyle,Alexander,Kyle Alexander,"Alexander, Kyle",K. Alexander,kyle-alexander,1996-10-21T00:00:00,Tennessee,Canada,...,Miami,kyle_alexander,2019,2019,Y,Y,Y,Undrafted,Undrafted,Undrafted
19,201571,D.J.,Augustin,D.J. Augustin,"Augustin, D.J.",D. Augustin,dj-augustin,1987-11-10T00:00:00,Texas-Austin,USA,...,Houston,d.j._augustin,2008,2021,N,Y,Y,2008,1,9
0,203500,Steven,Adams,Steven Adams,"Adams, Steven",S. Adams,steven-adams,1993-07-20T00:00:00,Pittsburgh,New Zealand,...,Memphis,steven_adams,2013,2021,N,Y,Y,2013,1,12
17,1627853,Ryan,Arcidiacono,Ryan Arcidiacono,"Arcidiacono, Ryan",R. Arcidiacono,ryan-arcidiacono,1994-03-26T00:00:00,Villanova,USA,...,Chicago,ryan_arcidiacono,2017,2021,Y,Y,Y,Undrafted,Undrafted,Undrafted
5,1628960,Grayson,Allen,Grayson Allen,"Allen, Grayson",G. Allen,grayson-allen,1995-10-08T00:00:00,Duke,USA,...,Milwaukee,grayson_allen,2018,2021,Y,Y,Y,2018,1,21
13,1628961,Kostas,Antetokounmpo,Kostas Antetokounmpo,"Antetokounmpo, Kostas",K. Antetokounmpo,kostas-antetokounmpo,1997-11-20T00:00:00,Dayton,Greece,...,Los Angeles,kostas_antetokounmpo,2018,2021,Y,Y,Y,2018,2,60
8,202329,Al-Farouq,Aminu,Al-Farouq Aminu,"Aminu, Al-Farouq",A. Aminu,al-farouq-aminu,1990-09-21T00:00:00,Wake Forest,USA,...,Chicago,al-farouq_aminu,2010,2021,N,Y,Y,2010,1,8
11,201583,Ryan,Anderson,Ryan Anderson,"Anderson, Ryan",R. Anderson,ryan-anderson,1988-05-06T00:00:00,California,USA,...,,ryan_anderson,2008,2019,N,Y,Y,2008,1,21
6,1628386,Jarrett,Allen,Jarrett Allen,"Allen, Jarrett",J. Allen,jarrett-allen,1998-04-21T00:00:00,Texas-Austin,USA,...,Cleveland,jarrett_allen,2017,2021,N,Y,Y,2017,1,22
12,203507,Giannis,Antetokounmpo,Giannis Antetokounmpo,"Antetokounmpo, Giannis",G. Antetokounmpo,giannis-antetokounmpo,1994-12-06T00:00:00,Filathlitikos,Greece,...,Milwaukee,giannis_antetokounmpo,2013,2021,N,Y,Y,2013,1,15
7,1628443,Kadeem,Allen,Kadeem Allen,"Allen, Kadeem",K. Allen,kadeem-allen,1993-01-15T00:00:00,Arizona,USA,...,,kadeem_allen,2017,2019,Y,Y,Y,2017,2,53
16,1628384,OG,Anunoby,OG Anunoby,"Anunoby, OG",O. Anunoby,og-anunoby,1997-07-17T00:00:00,Indiana,United Kingdom,...,Toronto,og_anunoby,2017,2021,N,Y,Y,2017,1,23
14,203648,Thanasis,Antetokounmpo,Thanasis Antetokounmpo,"Antetokounmpo, Thanasis",T. Antetokounmpo,thanasis-antetokounmpo,1992-07-18T00:00:00,Panathinaikos,Greece,...,Milwaukee,thanasis_antetokounmpo,2015,2021,Y,Y,Y,2014,2,51
18,2772,Trevor,Ariza,Trevor Ariza,"Ariza, Trevor",T. Ariza,trevor-ariza,1985-06-30T00:00:00,UCLA,USA,...,Los Angeles,trevor_ariza,2004,2021,N,Y,Y,2004,2,43
1,1628389,Bam,Adebayo,Bam Adebayo,"Adebayo, Bam",B. Adebayo,bam-adebayo,1997-07-18T00:00:00,Kentucky,USA,...,Miami,bam_adebayo,2017,2021,N,Y,Y,2017,1,14
9,1626147,Justin,Anderson,Justin Anderson,"Anderson, Justin",J. Anderson,justin-anderson,1993-11-19T00:00:00,Virginia,USA,...,Brooklyn,justin_anderson,2015,2019,Y,Y,Y,2015,1,21

## Create a Dataframe with Teams

In [14]:
from nba_api.stats.static import teams

In [15]:
# Get all teams.
nba_teams = teams.get_teams()
df = pd.DataFrame(nba_teams)
df

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

## Create a Dataframe with Player Career Stats

In [20]:
from nba_api.stats.endpoints import playercareerstats

In [22]:
# Bam Adebayo
career = playercareerstats.PlayerCareerStats(player_id='1628389')
df = career.get_data_frames()[0]
df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1628389,2017-18,00,1610612748,MIA,20.0,69,19,1368.0,174,...,0.721,118,263,381,101,32,41,66,138,477
1,1628389,2018-19,00,1610612748,MIA,21.0,82,28,1913.0,280,...,0.735,165,432,597,184,71,65,121,203,729
2,1628389,2019-20,00,1610612748,MIA,22.0,72,72,2417.0,440,...,0.691,176,559,735,368,82,93,204,182,1146
3,1628389,2020-21,00,1610612748,MIA,23.0,64,64,2143.0,456,...,0.799,142,431,573,346,75,66,169,145,1197

## Get Play-by-Play Data for a Given Game

In [23]:
from nba_api.stats.endpoints import leaguegamefinder

In [24]:
# get game logs from the reg season
gamefinder = leaguegamefinder.LeagueGameFinder(season_nullable='2020-21', 
                                              league_id_nullable='00', 
                                              season_type_nullable='Regular Season')
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22020,1610612744,GSW,Golden State Warriors,0022001070,2021-05-16,GSW vs. MEM,W,240,113,...,0.889,12,34,46,26,9,4,19,19,12.0
1,22020,1610612762,UTA,Utah Jazz,0022001077,2021-05-16,UTA @ SAC,W,239,121,...,0.840,9,41,50,28,9,3,16,14,22.0
2,22020,1610612764,WAS,Washington Wizards,0022001080,2021-05-16,WAS vs. CHA,W,241,115,...,0.810,10,43,53,22,4,3,14,20,5.0
3,22020,1610612756,PHX,Phoenix Suns,0022001078,2021-05-16,PHX @ SAS,W,240,123,...,1.000,10,38,48,36,7,5,8,13,2.0
4,22020,1610612750,MIN,Minnesota Timberwolves,0022001071,2021-05-16,MIN vs. DAL,W,241,136,...,0.840,11,27,38,35,11,4,9,22,15.0

In [25]:
# get a list of the distinct game_ids
game_ids = games['GAME_ID'].unique().tolist()

In [26]:
game_ids

['0022001070',
 '0022001077',
 '0022001080',
 '0022001078',
 '0022001071',
 '0022001068',
 '0022001074',
 '0022001069',
 '0022001075',
 '0022001079',
 '0022001073',
 '0022001067',
 '0022001072',
 '0022001076',
 '0022001066',
 '0022001061',
 '0022001060',
 '0022001063',
 '0022001062',
 '0022001064',
 '0022001065',
 '0022001057',
 '0022000263',
 '0022001056',
 '0022000204',
 '0022001054',
 '0022001059',
 '0022001055',
 '0022001058',
 '0022001051',
 '0022001047',
 '0022001050',
 '0022001048',
 '0022001049',
 '0022001052',
 '0022001053',
 '0022000458',
 '0022000255',
 '0022001043',
 '0022001046',
 '0022001044',
 '0022000154',
 '0022001045',
 '0022001042',
 '0022001038',
 '0022000448',
 '0022001034',
 '0022001032',
 '0022001035',
 '0022001041',
 '0022001037',
 '0022001039',
 '0022001036',
 '0022001033',
 '0022001040',
 '0022001030',
 '0022001027',
 '0022001028',
 '0022001026',
 '0022001029',
 '0022001031',
 '0022001025',
 '0022000145',
 '0022001020',
 '0022001022',
 '0022001023',
 '0022001019',
 '0022001021',
 '0022001024',
 '0022001013',
 '0022001016',
 '0022001015',
 '0022001018',
 '0022001017',
 '0022001014',
 '0022001012',
 '0022001010',
 '0022001004',
 '0022001005',
 '0022001008',
 '0022000160',
 '0022001011',
 '0022001006',
 '0022001009',
 '0022001003',
 '0022001007',
 '0022000999',
 '0022001002',
 '0022001001',
 '0022000998',
 '0022000997',
 '0022000434',
 '0022001000',
 '0022000995',
 '0022000235',
 '0022000992',
 '0022000990',
 '0022000993',
 '0022000996',
 '0022000994',
 '0022000183',
 '0022000991',
 '0022000985',
 '0022000987',
 '0022000988',
 '0022000984',
 '0022000989',
 '0022000983',
 '0022000986',
 '0022000977',
 '0022000980',
 '0022000982',
 '0022000978',
 '0022000981',
 '0022000979',
 '0022000976',
 '0022000975',
 '0022000972',
 '0022000974',
 '0022000971',
 '0022000967',
 '0022000968',
 '0022000973',
 '0022000970',
 '0022000969',
 '0022000965',
 '0022000961',
 '0022000966',
 '0022000962',
 '0022000960',
 '0022000963',
 '0022000958',
 '0022000957',
 '0022000959',
 '0022000964',
 '0022000950',
 '0022000951',
 '0022000956',
 '0022000949',
 '0022000954',
 '0022000953',
 '0022000952',
 '0022000955',
 '0022000947',
 '0022000946',
 '0022000943',
 '0022000945',
 '0022000948',
 '0022000944',
 '0022000942',
 '0022000941',
 '0022000937',
 '0022000938',
 '0022000933',
 '0022000939',
 '0022000934',
 '0022000936',
 '0022000940',
 '0022000935',
 '0022000930',
 '0022000932',
 '0022000931',
 '0022000927',
 '0022000929',
 '0022000928',
 '0022000918',
 '0022000922',
 '0022000924',
 '0022000917',
 '0022000923',
 '0022000919',
 '0022000926',
 '0022000920',
 '0022000916',
 '0022000921',
 '0022000925',
 '0022000914',
 '0022000911',
 '0022000240',
 '0022000915',
 '0022000912',
 '0022000913',
 '0022000197',
 '0022000910',
 '0022000264',
 '0022000909',
 '0022000904',
 '0022000906',
 '0022000907',
 '0022000908',
 '0022000905',
 '0022000903',
 '0022000225',
 '0022000898',
 '0022000900',
 '0022000899',
 '0022000901',
 '0022000902',
 '0022000892',
 '0022000897',
 '0022000896',
 '0022000894',
 '0022000895',
 '0022000893',
 '0022000886',
 '0022000884',
 '0022000890',
 '0022000885',
 '0022000442',
 '0022000889',
 '0022000883',
 '0022000882',
 '0022000888',
 '0022000891',
 '0022000887',
 '0022000881',
 '0022000880',
 '0022000876',
 '0022000878',
 '0022000879',
 '0022000877',
 '0022000870',
 '0022000473',
 '0022000875',
 '0022000868',
 '0022000873',
 '0022000872',
 '0022000874',
 '0022000869',
 '0022000871',
 '0022000362',
 '0022000862',
 '0022000863',
 '0022000866',
 '0022000867',
 '0022000861',
 '0022000864',
 '0022000865',
 '0022000858',
 '0022000856',
 '0022000855',
 '0022000859',
 '0022000857',
 '0022000860',
 '0022000848',
 '0022000851',
 '0022000847',
 '0022000845',
 '0022000852',
 '0022000846',
 '0022000849',
 '0022000844',
 '0022000854',
 '0022000853',
 '0022000850',
 '0022000840',
 '0022000842',
 '0022000841',
 '0022000843',
 '0022000839',
 '0022000838',
 '0022000461',
 '0022000837',
 '0022000834',
 '0022000836',
 '0022000832',
 '0022000829',
 '0022000830',
 '0022000831',
 '0022000833',
 '0022000835',
 '0022000825',
 '0022000823',
 '0022000828',
 '0022000824',
 '0022000827',
 '0022000826',
 '0022000817',
 '0022000821',
 '0022000822',
 '0022000816',
 '0022000819',
 '0022000278',
 '0022000818',
 '0022000815',
 '0022000820',
 '0022000812',
 '0022000813',
 '0022000809',
 '0022000814',
 '0022000810',
 '0022000811',
 '0022000805',
 '0022000806',
 '0022000808',
 '0022000807',
 '0022000801',
 '0022000199',
 '0022000802',
 '0022000800',
 '0022000803',
 '0022000794',
 '0022000804',
 '0022000792',
 '0022000796',
 '0022000795',
 '0022000790',
 '0022000797',
 '0022000798',
 '0022000799',
 '0022000791',
 '0022000793',
 '0022000523',
 '0022000785',
 '0022000787',
 '0022000784',
 '0022000786',
 '0022000789',
 '0022000788',
 '0022000776',
 '0022000780',
 '0022000778',
 '0022000782',
 '0022000783',
 '0022000779',
 '0022000456',
 '0022000781',
 '0022000777',
 '0022000773',
 '0022000321',
 '0022000774',
 '0022000769',
 '0022000772',
 '0022000775',
 '0022000771',
 '0022000770',
 '0022000768',
 '0022000764',
 '0022000766',
 '0022000763',
 '0022000767',
 '0022000765',
 '0022000762',
 '0022000755',
 '0022000759',
 '0022000756',
 '0022000761',
 '0022000757',
 '0022000760',
 '0022000758',
 '0022000748',
 '0022000750',
 '0022000753',
 '0022000752',
 '0022000749',
 '0022000754',
 '0022000747',
 '0022000751',
 '0022000739',
 '0022000746',
 '0022000741',
 '0022000743',
 '0022000740',
 '0022000737',
 '0022000745',
 '0022000738',
 '0022000742',
 '0022000744',
 '0022000735',
 '0022000732',
 '0022000179',
 '0022000736',
 '0022000731',
 '0022000734',
 '0022000733',
 '0022000723',
 '0022000730',
 '0022000721',
 '0022000724',
 '0022000722',
 '0022000728',
 '0022000727',
 '0022000729',
 '0022000725',
 '0022000726',
 '0022000171',
 '0022000720',
 '0022000718',
 '0022000719',
 '0022000713',
 '0022000711',
 '0022000708',
 '0022000714',
 '0022000707',
 '0022000709',
 '0022000710',
 '0022000716',
 '0022000717',
 '0022000715',
 '0022000712',
 '0022000703',
 '0022000706',
 '0022000704',
 '0022000705',
 '0022000694',
 '0022000702',
 '0022000700',
 '0022000698',
 '0022000699',
 '0022000695',
 '0022000697',
 '0022000696',
 '0022000701',
 '0022000687',
 '0022000683',
 '0022000692',
 '0022000690',
 '0022000684',
 '0022000691',
 '0022000689',
 '0022000693',
 '0022000688',
 '0022000685',
 '0022000686',
 '0022000678',
 '0022000680',
 '0022000681',
 '0022000682',
 '0022000679',
 '0022000677',
 '0022000669',
 '0022000672',
 '0022000671',
 '0022000667',
 '0022000673',
 '0022000670',
 '0022000674',
 '0022000675',
 '0022000676',
 '0022000668',
 '0022000666',
 '0022000665',
 '0022000662',
 '0022000663',
 '0022000661',
 '0022000664',
 '0022000658',
 '0022000657',
 '0022000655',
 '0022000656',
 '0022000653',
 '0022000660',
 '0022000659',
 '0022000654',
 '0022000016',
 '0022000652',
 '0022000650',
 '0022000646',
 '0022000649',
 '0022000648',
 '0022000645',
 '0022000647',
 '0022000167',
 '0022000651',
 '0022000644',
 '0022000643',
 '0022000640',
 '0022000641',
 '0022000642',
 '0022000632',
 '0022000639',
 '0022000634',
 '0022000633',
 '0022000637',
 '0022000435',
 '0022000638',
 '0022000631',
 '0022000635',
 '0022000636',
 '0022000166',
 '0022000628',
 '0022000627',
 '0022000629',
 '0022000626',
 '0022000630',
 '0022000621',
 '0022000624',
 '0022000617',
 '0022000622',
 '0022000623',
 '0022000620',
 '0022000616',
 '0022000625',
 '0022000618',
 '0022000619',
 '0022000610',
 '0022000613',
 '0022000614',
 '0022000615',
 '0022000609',
 '0022000612',
 '0022000611',
 '0022000607',
 '0022000602',
 '0022000428',
 '0022000605',
 '0022000604',
 '0022000608',
 '0022000606',
 '0022000603',
 '0022000595',
 '0022000593',
 '0022000594',
 '0022000598',
 '0022000597',
 '0022000599',
 '0022000596',
 '0022000600',
 '0022000601',
 '0022000194',
 '0022000592',
 '0022000591',
 '0022000589',
 '0022000586',
 '0022000590',
 '0022000588',
 '0022000587',
 '0022000585',
 '0022000582',
 '0022000581',
 '0022000579',
 '0022000580',
 '0022000583',
 '0022000584',
 '0022000578',
 '0022000575',
 '0022000572',
 '0022000570',
 '0022000577',
 '0022000568',
 '0022000574',
 '0022000571',
 '0022000576',
 '0022000569',
 '0022000573',
 '0022000567',
 '0022000566',
 '0022000185',
 '0022000555',
 '0022000554',
 '0022000558',
 '0022000556',
 '0022000553',
 '0022000557',
 '0022000552',
 '0022000565',
 '0022000539',
 '0022000550',
 '0022000546',
 '0022000547',
 '0022000549',
 '0022000545',
 '0022000548',
 '0022000544',
 '0022000551',
 '0022000543',
 '0022000542',
 '0022000537',
 '0022000540',
 '0022000541',
 '0022000536',
 '0022000538',
 '0022000531',
 '0022000530',
 '0022000534',
 '0022000533',
 '0022000532',
 '0022000529',
 '0022000535',
 '0022000527',
 '0022000528',
 '0022000526',
 '0022000524',
 '0022000525',
 '0022000520',
 '0022000522',
 '0022000521',
 '0022000516',
 '0022000517',
 '0022000513',
 '0022000518',
 '0022000515',
 '0022000519',
 '0022000514',
 '0022000505',
 '0022000510',
 '0022000512',
 '0022000509',
 '0022000511',
 '0022000504',
 '0022000506',
 '0022000507',
 '0022000508',
 '0022000500',
 '0022000499',
 '0022000503',
 '0022000502',
 '0022000501',
 '0022000498',
 '0022000495',
 '0022000492',
 '0022000491',
 '0022000494',
 '0022000489',
 '0022000490',
 '0022000497',
 '0022000493',
 '0022000496',
 '0022000480',
 '0022000482',
 '0022000487',
 '0022000488',
 '0022000486',
 '0022000484',
 '0022000481',
 '0022000485',
 '0022000483',
 '0022000477',
 '0022000479',
 '0022000474',
 '0022000475',
 '0022000478',
 '0022000476',
 '0022000465',
 '0022000472',
 '0022000469',
 '0022000471',
 '0022000468',
 '0022000470',
 '0022000467',
 '0022000466',
 '0022000459',
 '0022000462',
 '0022000460',
 '0022000464',
 '0022000463',
 '0022000449',
 '0022000450',
 '0022000452',
 '0022000451',
 '0022000563',
 '0022000453',
 '0022000457',
 '0022000455',
 '0022000454',
 '0022000447',
 '0022000445',
 '0022000446',
 '0022000439',
 '0022000562',
 '0022000441',
 '0022000444',
 '0022000443',
 '0022000438',
 '0022000437',
 '0022000564',
 '0022000436',
 '0022000440',
 '0022000433',
 '0022000427',
 '0022000429',
 '0022000430',
 '0022000432',
 '0022000431',
 '0022000426',
 '0022000425',
 '0022000423',
 '0022000422',
 '0022000424',
 '0022000420',
 '0022000421',
 '0022000413',
 '0022000417',
 '0022000560',
 '0022000561',
 '0022000416',
 '0022000411',
 '0022000414',
 '0022000419',
 '0022000415',
 '0022000418',
 '0022000408',
 '0022000407',
 '0022000409',
 '0022000406',
 '0022000410',
 '0022000396',
 '0022000395',
 '0022000402',
 '0022000405',
 '0022000397',
 '0022000399',
 '0022000404',
 '0022000400',
 '0022000401',
 '0022000403',
 '0022000412',
 '0022000394',
 '0022000391',
 '0022000393',
 '0022000398',
 '0022000392',
 '0022000389',
 '0022000387',
 '0022000388',
 '0022000383',
 '0022000386',
 '0022000390',
 '0022000385',
 '0022000384',
 '0022000382',
 '0022000376',
 '0022000377',
 '0022000379',
 '0022000381',
 '0022000375',
 '0022000380',
 '0022000378',
 '0022000367',
 '0022000371',
 '0022000370',
 '0022000372',
 '0022000373',
 '0022000374',
 '0022000369',
 '0022000368',
 '0022000364',
 '0022000363',
 '0022000215',
 '0022000366',
 '0022000365',
 '0022000351',
 '0022000360',
 '0022000357',
 '0022000353',
 '0022000355',
 '0022000359',
 '0022000358',
 '0022000361',
 '0022000352',
 '0022000356',
 '0022000354',
 '0022000349',
 '0022000344',
 '0022000346',
 '0022000345',
 '0022000342',
 '0022000347',
 '0022000350',
 '0022000343',
 '0022000348',
 '0022000339',
 '0022000337',
 '0022000341',
 '0022000338',
 '0022000340',
 '0022000329',
 '0022000327',
 '0022000336',
 '0022000334',
 '0022000333',
 '0022000335',
 '0022000328',
 '0022000331',
 '0022000332',
 '0022000330',
 '0022000323',
 '0022000326',
 '0022000559',
 '0022000322',
 '0022000325',
 '0022000324',
 '0022000319',
 '0022000313',
 '0022000316',
 '0022000320',
 '0022000315',
 '0022000318',
 '0022000317',
 '0022000314',
 '0022000312',
 '0022000308',
 '0022000307',
 '0022000310',
 '0022000306',
 '0022000309',
 '0022000311',
 '0022000299',
 '0022000302',
 '0022000298',
 '0022000305',
 '0022000304',
 '0022000300',
 '0022000303',
 '0022000301',
 '0022000292',
 '0022000288',
 '0022000293',
 '0022000294',
 '0022000291',
 '0022000297',
 '0022000290',
 '0022000289',
 '0022000295',
 '0022000296',
 '0022000286',
 '0022000285',
 '0022000287',
 '0022000284',
 '0022000271',
 '0022000279',
 '0022000280',
 '0022000274',
 '0022000282',
 '0022000277',
 '0022000276',
 '0022000283',
 '0022000273',
 '0022000275',
 '0022000281',
 '0022000272',
 '0022000270',
 '0022000269',
 '0022000268',
 '0022000257',
 '0022000267',
 '0022000260',
 '0022000262',
 '0022000258',
 '0022000259',
 '0022000261',
 '0022000266',
 '0022000265',
 '0022000253',
 '0022000251',
 '0022000252',
 '0022000256',
 '0022000250',
 '0022000249',
 '0022000254',
 '0022000245',
 '0022000246',
 '0022000244',
 '0022000243',
 '0022000247',
 '0022000248',
 '0022000242',
 '0022000230',
 '0022000229',
 '0022000236',
 '0022000239',
 '0022000234',
 '0022000237',
 '0022000231',
 '0022000238',
 '0022000241',
 '0022000232',
 '0022000233',
 '0022000228',
 '0022000226',
 '0022000227',
 '0022000223',
 '0022000220',
 '0022000224',
 '0022000218',
 '0022000222',
 '0022000217',
 '0022000221',
 '0022000216',
 '0022000219',
 '0022000214',
 '0022000213',
 '0022000209',
 '0022000206',
 '0022000212',
 '0022000207',
 '0022000211',
 '0022000208',
 '0022000205',
 '0022000203',
 '0022000210',
 '0022000202',
 '0022000198',
 '0022000200',
 '0022000196',
 '0022000201',
 '0022000193',
 '0022000190',
 '0022000191',
 '0022000189',
 '0022000195',
 '0022000192',
 '0022000186',
 '0022000184',
 '0022000187',
 '0022000180',
 '0022000188',
 '0022000181',
 '0022000182',
 '0022000178',
 '0022000175',
 '0022000176',
 '0022000174',
 '0022000177',
 '0022000170',
 '0022000164',
 '0022000173',
 '0022000168',
 '0022000172',
 '0022000169',
 '0022000165',
 '0022000158',
 '0022000162',
 '0022000163',
 '0022000157',
 '0022000161',
 '0022000159',
 '0022000150',
 '0022000152',
 '0022000149',
 '0022000155',
 '0022000151',
 '0022000156',
 '0022000153',
 '0022000143',
 '0022000142',
 '0022000147',
 '0022000146',
 '0022000148',
 '0022000141',
 '0022000144',
 '0022000138',
 '0022000137',
 '0022000135',
 '0022000133',
 '0022000139',
 '0022000136',
 '0022000134',
 '0022000140',
 '0022000132',
 '0022000131',
 '0022000129',
 '0022000123',
 '0022000124',
 '0022000128',
 '0022000126',
 '0022000130',
 '0022000125',
 '0022000127',
 '0022000122',
 '0022000121',
 '0022000119',
 '0022000120',
 '0022000118',
 '0022000113',
 '0022000111',
 '0022000112',
 '0022000115',
 '0022000109',
 '0022000116',
 '0022000108',
 '0022000110',
 '0022000114',
 '0022000107',
 '0022000117',
 '0022000106',
 '0022000105',
 '0022000102',
 '0022000103',
 '0022000104',
 '0022000101',
 '0022000095',
 '0022000099',
 '0022000097',
 '0022000098',
 '0022000093',
 '0022000100',
 '0022000096',
 '0022000094',
 '0022000090',
 '0022000087',
 '0022000088',
 '0022000092',
 '0022000086',
 '0022000085',
 '0022000089',
 '0022000091',
 '0022000083',
 '0022000081',
 '0022000084',
 ...]

In [27]:
game_id = '0022000776'

In [28]:
from nba_api.stats.endpoints import playbyplayv2
pbp = playbyplayv2.PlayByPlayV2(game_id)
pbp = pbp.get_data_frames()[0]
pbp.head()

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,0022000776,2,12,0,1,7:11 PM,12:00,None,Start of 1st Period (7:11 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,0
1,0022000776,4,10,0,1,7:11 PM,12:00,Jump Ball Bitadze vs. Towns: Tip to Rubio,None,None,...,Timberwolves,MIN,5,201937,Ricky Rubio,1.610613e+09,Minnesota,Timberwolves,MIN,1
2,0022000776,7,5,45,1,7:11 PM,11:45,None,None,Towns Out of Bounds - Bad Pass Turnover Turnov...,...,None,None,1,0,None,NaN,None,None,None,1
3,0022000776,8,2,5,1,7:11 PM,11:31,MISS Bitadze 5' Layup,None,Towns BLOCK (1 BLK),...,None,None,5,1626157,Karl-Anthony Towns,1.610613e+09,Minnesota,Timberwolves,MIN,1
4,0022000776,10,4,0,1,7:11 PM,11:28,None,None,Rubio REBOUND (Off:0 Def:1),...,None,None,0,0,None,NaN,None,None,None,1

In [29]:
pbp.tail(10)

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
475,0022000776,690,1,79,4,9:28 PM,0:10,None,None,Russell 27' 3PT Pullup Jump Shot (17 PTS) (Rub...,...,Timberwolves,MIN,0,0,None,NaN,None,None,None,1
476,0022000776,692,9,1,4,9:28 PM,0:09,PACERS Timeout: Regular (Full 7 Short 0),None,None,...,None,None,0,0,None,NaN,None,None,None,0
477,0022000776,693,8,0,4,9:29 PM,0:09,SUB: McDermott FOR Sampson,None,None,...,Pacers,IND,0,0,None,NaN,None,None,None,0
478,0022000776,695,6,28,4,9:30 PM,0:08,None,None,Edwards Personal Take Foul (P1.PN) (J.Tiven),...,Pacers,IND,1,0,None,NaN,None,None,None,1
479,0022000776,697,3,11,4,9:30 PM,0:08,Holiday Free Throw 1 of 2 (21 PTS),None,None,...,None,None,0,0,None,NaN,None,None,None,1
480,0022000776,698,8,0,4,9:30 PM,0:08,SUB: Sampson FOR McDermott,None,None,...,Pacers,IND,0,0,None,NaN,None,None,None,0
481,0022000776,700,3,12,4,9:31 PM,0:08,Holiday Free Throw 2 of 2 (22 PTS),None,None,...,None,None,0,0,None,NaN,None,None,None,1
482,0022000776,701,2,1,4,9:31 PM,0:01,None,None,MISS Russell 26' 3PT Jump Shot,...,None,None,0,0,None,NaN,None,None,None,1
483,0022000776,702,4,0,4,9:31 PM,0:01,McConnell REBOUND (Off:1 Def:2),None,None,...,None,None,0,0,None,NaN,None,None,None,1
484,0022000776,703,13,0,4,9:31 PM,0:00,None,End of 4th Period (9:31 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,1

## Get Box Score Data for a Given Game

In [30]:
from nba_api.stats.endpoints import boxscoretraditionalv2

In [32]:
player_stat_data = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id)
stats_df = player_stat_data.get_data_frames()[0]
stats_df.tail()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
21,0022000776,1610612754,IND,Indiana,203087,Jeremy Lamb,Jeremy,,,20:10,...,0.0,4.0,4.0,0.0,1.0,3.0,2.0,2.0,7.0,14.0
22,0022000776,1610612754,IND,Indiana,1629103,Kelan Martin,Kelan,,,13:21,...,1.0,5.0,6.0,1.0,1.0,0.0,1.0,1.0,5.0,10.0
23,0022000776,1610612754,IND,Indiana,1629052,Oshae Brissett,Oshae,,,2:01,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0
24,0022000776,1610612754,IND,Indiana,1628968,Brian Bowen II,Brian,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0022000776,1610612754,IND,Indiana,1630199,Cassius Stanley,Cassius,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# create function that gets box score data based on game_ids
def get_box_score_data(game_id):
    player_stat_data = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id, headers=headers, timeout=100)
    df = player_stat_data.player_stats.get_data_frame()
    return df

In [34]:
# using this for testing purposes only
sample_game_ids = [
    '0022001070',
    '0022001077',
    '0022001068',
    '0022001074']

In [35]:
boxscores = []
#for game_id in game_ids: # remove this when ready to run for full season
for game_id in sample_game_ids:
    boxscore_data = get_box_score_data(game_id)
    boxscores.append(boxscore_data)

final_df = pd.concat(boxscores, ignore_index=True)

In [36]:
final_df.sample(10)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
26,0022001070,1610612744,GSW,Golden State,1627780,Gary Payton II,Gary,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,0022001068,1610612741,CHI,Chicago,1629653,Devon Dotson,Devon,,,21:25,...,0.0,2.0,2.0,4.0,1.0,0.0,0.0,2.0,11.0,13.0
100,0022001074,1610612760,OKC,Oklahoma City,1630197,Aleksej Pokusevski,Aleksej,G,,40:55,...,0.0,8.0,8.0,2.0,0.0,0.0,7.0,1.0,29.0,2.0
88,0022001074,1610612746,LAC,LA,1630187,Daniel Oturu,Daniel,,,37:09,...,7.0,5.0,12.0,2.0,2.0,1.0,2.0,3.0,13.0,-2.0
93,0022001074,1610612746,LAC,LA,202331,Paul George,Paul,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,0022001074,1610612760,OKC,Oklahoma City,1628396,Tony Bradley,Tony,,,14:07,...,2.0,5.0,7.0,1.0,0.0,2.0,0.0,0.0,8.0,8.0
50,0022001077,1610612758,SAC,Sacramento,1629657,Kyle Guy,Kyle,,,18:38,...,0.0,6.0,6.0,5.0,2.0,0.0,1.0,2.0,6.0,-13.0
2,0022001070,1610612763,MEM,Memphis,202685,Jonas Valanciunas,Jonas,C,,35:30,...,6.0,10.0,16.0,1.0,1.0,0.0,1.0,2.0,29.0,-13.0
80,0022001068,1610612741,CHI,Chicago,202329,Al-Farouq Aminu,Al-Farouq,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,0022001077,1610612762,UTA,Utah,202324,Derrick Favors,Derrick,,,17:11,...,1.0,8.0,9.0,0.0,1.0,0.0,1.0,1.0,10.0,-8.0

## Get 2020-21 Play-by-Play Data using Game Ids

In [37]:
# create function that gets pbp logs from the 2020-21 season
def get_data(game_id):
    play_by_play_url = "https://cdn.nba.com/static/json/liveData/playbyplay/playbyplay_"+game_id+".json"
    response = requests.get(url=play_by_play_url, headers=headers).json()
    play_by_play = response['game']['actions']
    df = pd.DataFrame(play_by_play)
    df['gameid'] = game_id
    return df

In [38]:
# using this for testing purposes only
sample_game_ids = [
    '0022001070',
    '0022001077',
    '0022001068',
    '0022001074']

In [39]:
pbpdata = []
#for game_id in game_ids: # remove this when ready to run for full season
for game_id in sample_game_ids:
    game_data = get_data(game_id)
    pbpdata.append(game_data)

final_df = pd.concat(pbpdata, ignore_index=True)

In [40]:
final_df

,actionNumber,clock,timeActual,period,periodType,actionType,subType,qualifiers,personId,x,...,foulTechnicalTotal,foulDrawnPlayerName,foulDrawnPersonId,turnoverTotal,stealPlayerName,stealPersonId,blockPlayerName,blockPersonId,value,gameid
0,2,PT12M00.00S,2021-05-16T19:42:02.5Z,1,REGULAR,period,start,[],0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001070
1,4,PT11M58.00S,2021-05-16T19:42:04.5Z,1,REGULAR,jumpball,recovered,[],1628991,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001070
2,7,PT11M45.00S,2021-05-16T19:42:17.1Z,1,REGULAR,2pt,Layup,[pointsinthepaint],1628415,90.883706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001070
3,9,PT11M27.00S,2021-05-16T19:42:33.6Z,1,REGULAR,3pt,Jump Shot,[],203110,29.385677,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001070
4,10,PT11M25.00S,2021-05-16T19:42:37.3Z,1,REGULAR,rebound,offensive,[],1626172,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2205,598,PT00M05.40S,2021-05-17T03:09:01.8Z,4,REGULAR,2pt,DUNK,"[pointsinthepaint, 2ndchance]",1629650,94.410000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001074
2206,599,PT00M00.80S,2021-05-17T03:09:08.5Z,4,REGULAR,3pt,Jump Shot,[],1628379,31.093955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001074
2207,600,PT00M00.80S,2021-05-17T03:09:08.5Z,4,REGULAR,rebound,offensive,[team],0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001074
2208,601,PT00M00.00S,2021-05-17T03:09:52.1Z,4,REGULAR,period,end,[],0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001074
2209,602,PT00M00.00S,2021-05-17T03:09:53.8Z,4,REGULAR,game,end,[],0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0022001074